networks:
  web:

services:
  backend:
    image: qxbrokerapi
    build:
      context: .
      dockerfile: ./Qxbroker.API/Dockerfile
    environment:
      - ASPNETCORE_ENVIRONMENT=RELEASE
      - MongoDB__ConnectionString=mongodb://mongo:27017
      - Redis__ConnectionString=redis:6379
    depends_on:
      - mongo
      - redis
    volumes:
      - static-files:/app/StaticFiles
    networks:
      - web

  frontend:
    image: qxbrokerclient
    build:
      context: ./qxbroker.client
      dockerfile: Dockerfile
    networks:
      - web

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
    volumes:
      - './nginx.conf:/etc/nginx/nginx.conf'
      - static-files:/app/StaticFiles
    networks:
      - web
    

  mongo:
    image: mongo:latest
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo-data:/data/db
    restart: always
    networks:
      - web

  redis:
    image: redis:latest
    container_name: redis
    ports:
      - "6379:6379"
    restart: always
    networks:
      - web

volumes:
  mongo-data:
  static-files:
